// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

// Injectors from wire.go:

func InitializedApp() (IPillar, error) {
	iPillar := ProvideGinEngine()
	return iPillar, nil
}
