// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"simpleGinAPI/internal/controller"
	"simpleGinAPI/internal/routes"
)

// Injectors from wire.go:

func InitializedApp() (IPillar, error) {
	iAuthController := controller.ProvideAuthController()
	authRouter := routes.ProvideAuthRouter(iAuthController)
	iRouter := routes.ProvideRouter(authRouter)
	iPillar := ProvideGinEngine(iRouter)
	return iPillar, nil
}
